### ISSUE TITLE
Feature Addition request- Add Image widget

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/FlutterFolio#2]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | 🚀 Flutter's Widget Wonderland! Explore, Learn, Create. Your one-stop for all things Flutter widgets! 📱✨ |
| Label  | Add Image Widget|

---

### Issue Title
Add Image Widget

#### Overview
This issue aims to add the "Image" widget to the FlutterFolio widget catalog app. The "Image" widget is a fundamental component in Flutter for displaying images.

#### Adhere to the below folder structure for reference
```
- lib/
  - screens/
    - home_screen.dart
    - widget_detail_screen.dart
  - models/
    - widget_models.dart
  - main.dart
  - assets/
  - images/
    - flutter_logo.png
  - data/
    - widgets_data.dart
  - theme
    - app_theme.dart
- README.md

```

#### Task
- Create a new widget for the "Image" in the `lib/widgets` folder.
- Implement the "Image" widget with the ability to load and display images from various sources, such as assets or network URLs.
- Add the "Image" widget to the `widget_data.dart` data source with the widget's name, description, and image path.
- Update the `home_screen.dart` to dynamically generate an elevated button for the "Image" widget.

#### Acceptance Criteria
- The "Image" widget is created and can load and display images.
- It is added to the widget catalog with a proper description and an image that represents the widget.
- Users can access information about the "Image" widget through the app's user interface.

#### Definition of Done
- The "Image" widget code is clean, well-documented, and follows Flutter best practices.
- The widget is tested and functions correctly.
- The widget is accessible through the app's user interface.
- The issue is reviewed and accepted.

### Labels
- enhancement
- widget

**Comment by ayoitsamishaa** [comment]
Hello, I'd like to work on this. Can you please assign this to me?

**Comment by Tejoooo** [comment]
@ShubhKanodia Can u assign me this issue I wld love to work on this
