### ISSUE TITLE
Feature Addition request- Add AppBar widget

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/FlutterFolio#3]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | 🚀 Flutter's Widget Wonderland! Explore, Learn, Create. Your one-stop for all things Flutter widgets! 📱✨ |
| Label  | Add AppBar Widget|

---

### Issue Title
Add AppBar Widget

#### Overview
This issue is about adding an "AppBar" widget to the FlutterFolio widget catalog app. The "AppBar" widget is a common UI component in Flutter for displaying the app's title, leading actions, and actions.

#### Adhere to the below folder structure for reference
```
- lib/
  - screens/
    - home_screen.dart
    - widget_detail_screen.dart
  - models/
    - widget_models.dart
  - main.dart
  - assets/
  - images/
    - flutter_logo.png
  - data/
    - widgets_data.dart
  - theme
    - app_theme.dart
- README.md

```

#### Task
- Create a new widget for the "AppBar" in the `lib/widgets` folder.
- Implement the "AppBar" widget with the ability to customize its title, leading actions, and actions.
- Add the "AppBar" widget to the `widget_data.dart` data source with the widget's name, description, and image path.
- Update the `home_screen.dart` to dynamically generate an elevated button for the "AppBar" widget.

#### Acceptance Criteria
- The "AppBar" widget is created and can display a customizable title, leading actions, and actions.
- It is added to the widget catalog with a proper description and an image that represents the widget.
- Users can access information about the "AppBar" widget through the app's user interface.

#### Definition of Done
- The "AppBar" widget code is clean, well-documented, and follows Flutter best practices.
- The widget is tested and functions correctly.
- The widget is accessible through the app's user interface.
- The issue is reviewed and accepted.

**Comment by abhinavs1920** [comment]
Please assign this issue to me.
