### ISSUE TITLE
Feature Addition request- Add Scaffold widget

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/FlutterFolio#4]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | 🚀 Flutter's Widget Wonderland! Explore, Learn, Create. Your one-stop for all things Flutter widgets! 📱✨ |
| Label  | Add Scaffold Widget|

---

### Issue Title
Add Scaffold Widget

#### Overview
This issue is about adding a "Scaffold" widget to the FlutterFolio widget catalog app. The "Scaffold" widget is a fundamental component in Flutter for building the basic structure of app screens, including app bars, body content, and more.

#### Adhere to the below folder structure for reference
```
- lib/
  - screens/
    - home_screen.dart
    - widget_detail_screen.dart
  - models/
    - widget_models.dart
  - main.dart
  - assets/
  - images/
    - flutter_logo.png
  - data/
    - widgets_data.dart
  - theme
    - app_theme.dart
- README.md

```

#### Task
- Create a new widget for the "Scaffold" in the `lib/widgets` folder.
- Implement the "Scaffold" widget with customizable app bars, body content, and other scaffold elements.
- Add the "Scaffold" widget to the `widget_data.dart` data source with the widget's name, description, and image path.
- Update the `home_screen.dart` to dynamically generate an elevated button for the "Scaffold" widget.

#### Acceptance Criteria
- The "Scaffold" widget is created and can build the basic structure of app screens with customizable app bars, body content, and scaffold elements.
- It is added to the widget catalog with a proper description and an image that represents the widget.
- Users can access information about the "Scaffold" widget through the app's user interface.

#### Definition of Done
- The "Scaffold" widget code is clean, well-documented, and follows Flutter best practices.
- The widget is tested and functions correctly.
- The widget is accessible through the app's user interface.
- The issue is reviewed and accepted.

**Comment by ayoitsamishaa** [comment]
Hello, I'd like to work on this. Can you please assign this to me?
