### ISSUE TITLE
Feature Addition request- Add Text widget

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/FlutterFolio#5]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | 🚀 Flutter's Widget Wonderland! Explore, Learn, Create. Your one-stop for all things Flutter widgets! 📱✨ |
| Label  | Add Text Widget|

---

### Issue Title
Add Container Widget

#### Overview
This issue is about adding a "Container" widget to the FlutterFolio widget catalog app. The "Container" widget is a fundamental building block in Flutter for layout and styling.

#### Adhere to the below folder structure for reference
```
- lib/
  - screens/
    - home_screen.dart
    - widget_detail_screen.dart
  - models/
    - widget_models.dart
  - main.dart
  - assets/
  - images/
    - flutter_logo.png
  - data/
    - widgets_data.dart
  - theme
    - app_theme.dart
- README.md

```

#### Task
- Create a new widget for the "Text" in the `lib/widgets` folder.
- Implement the "Text" widget with customizable properties like fontstyle, color, weight etc.
- Add the "Text" widget to the `Text` data source with the widget's name, description, and image path.
- Update the `home_screen.dart` to dynamically generate an elevated button for the "Text" widget.

#### Acceptance Criteria
- The "Container" widget is created and functions as expected.
- It is added to the widget catalog with a proper description and an image that represents the widget.
- Users can access information about the "Text" widget through the app's user interface.

#### Definition of Done
- The "Text" widget code is clean, well-documented, and follows Flutter best practices.
- The widget is tested and functions correctly.
- The widget is accessible through the app's user interface.
- The issue is reviewed and accepted.

**Comment by abhinavs1920** [comment]
Please assign issue to me. I have started working on it

**Comment by VETREA** [comment]
@ShubhKanodia 
i have created the pr for this

**Comment by Vasanth-seemakurthy** [comment]
pls assign this issue to me @ShubhKanodia
