### ISSUE TITLE
Feature Addition request- Add Container

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/FlutterFolio#6]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | 🚀 Flutter's Widget Wonderland! Explore, Learn, Create. Your one-stop for all things Flutter widgets! 📱✨ |
| Label  | Add Container|

---

### Issue Title
Add Container Widget

#### Overview
This issue is about adding a "Container" widget to the FlutterFolio widget catalog app. The "Container" widget is a fundamental building block in Flutter for layout and styling.

#### Adhere to the below folder structure for reference
```
- lib/
  - screens/
    - home_screen.dart
    - widget_detail_screen.dart
  - models/
    - widget_models.dart
  - main.dart
  - assets/
  - images/
    - flutter_logo.png
  - data/
    - widgets_data.dart
  - theme
    - app_theme.dart
- README.md

```

#### Task
- Create a new widget for the "Container" in the `lib/widgets` folder.
- Implement the "Container" widget with customizable properties like padding, margin, and decoration.
- Add the "Container" widget to the `widget_data.dart` data source with the widget's name, description, and image path.
- Update the `home_screen.dart` to dynamically generate an elevated button for the "Container" widget.

#### Acceptance Criteria
- The "Container" widget is created and functions as expected.
- It is added to the widget catalog with a proper description and an image that represents the widget.
- Users can access information about the "Container" widget through the app's user interface.

#### Definition of Done
- The "Container" widget code is clean, well-documented, and follows Flutter best practices.
- The widget is tested and functions correctly.
- The widget is accessible through the app's user interface.
- The issue is reviewed and accepted.

**Comment by abhinavs1920** [comment]
I want to work on this issue. Please assign it to me.

**Comment by LeShaurya** [comment]
I want to work on this issue. Please assign it to me. @ShubhKanodia
